Repository LT-Students/DigitalOffice-ProjectService, pull requests merged in 2021-07, with the labels that each got.

#58 Add task property endpoints
  src/ProjectService.Business/Commands/CreateProjectCommand.cs
  src/ProjectService.Business/Commands/EditProjectCommand.cs
  src/ProjectService.Business/Commands/Task/CreateTaskCommand.cs
  src/ProjectService.Business/Commands/Task/CreateTaskPropertyCommand.cs
  src/ProjectService.Business/Commands/Task/EditTaskCommand.cs
  src/ProjectService.Business/Commands/Task/FindTaskPropertyCommand.cs
  src/ProjectService.Business/Commands/Task/FindTasksCommand.cs
  src/ProjectService.Business/Commands/Task/Interfaces/ICreateTaskCommand.cs
  src/ProjectService.Business/Commands/Task/Interfaces/ICreateTaskPropertyCommand.cs
  src/ProjectService.Business/Commands/Task/Interfaces/IEditTaskCommand.cs
  src/ProjectService.Business/Commands/Task/Interfaces/IFindTaskPropertyCommand.cs
  src/ProjectService.Business/Commands/Task/Interfaces/IFindTasksCommand.cs
  src/ProjectService.Data/Interfaces/ITaskPropertyRepository.cs
  src/ProjectService.Data/TaskPropertyRepository.cs
  src/ProjectService.Mappers/Models/Interfaces/ITaskPropertyInfoMapper.cs
  src/ProjectService.Mappers/Models/TaskPropertyInfoMapper.cs
  src/ProjectService.Mappers/RequestsMappers/DbTaskPropertyMapper.cs
  src/ProjectService.Mappers/RequestsMappers/Interfaces/IDbTaskPropertyMapper.cs
  src/ProjectService.Models.Dto/Enums/OperationResultStatusType.cs
  src/ProjectService.Models.Dto/Models/TaskProperty.cs
  src/ProjectService.Models.Dto/Models/TaskPropertyInfo.cs
  src/ProjectService.Models.Dto/Requests/CreateTaskPropertyRequest.cs
  src/ProjectService.Models.Dto/Requests/Filters/FindTaskPropertiesFilter.cs
  src/ProjectService.Models.Dto/Responses/OperationResultResponse.cs
  src/ProjectService.Validation/CreateTaskPropertyValidator.cs
  src/ProjectService.Validation/Interfaces/ICreateTaskPropertyValidator.cs
  src/ProjectService/Controllers/TaskPropertyController.cs
  src/ProjectService/Startup.cs
  test/ProjectService.Business.UnitTests/Commands/CreateProjectCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/CreateTaskCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/CreateTaskPropertyCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/DisableWorkersInProjectCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/EditProjectCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/EditTaskCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/FindProjectsCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/FindTaskPropertyCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/FindTasksCommandTests.cs
  test/ProjectService.Data.UnitTests/TaskPropertyRepositoryTests.cs
  test/ProjectService.Mappers.UnitTests/Models/TaskPropertyMapperInfoTests.cs
  test/ProjectService.Mappers.UnitTests/RequestsMappers/DbTaskPropertyMapperTests.cs
  test/ProjectService.Validation.UnitTests/CreateTaskPropertyValidatorTests.cs
Labels: enhancement

#57 Update CreateProjectCommand
  Common.Configurations.targets
  src/ProjectService.Business/Commands/CreateProjectCommand.cs
  src/ProjectService.Models.Dto/Configurations/RabbitMqConfig.cs
  src/ProjectService/appsettings.json
  test/ProjectService.Business.UnitTests/Commands/CreateProjectCommandTests.cs
Labels: enhancement

#59 Fixed get users
  src/ProjectService.Business/Commands/GetProjectCommand.cs
Labels: bug

#61 Fix create task
  src/ProjectService.Business/Commands/Task/CreateTaskCommand.cs
  src/ProjectService.Data.Provider.MsSql.Ef/Migrations/20210707003534_ChangeTaskPropertiesTableColumn.cs
  src/ProjectService.Mappers/RequestsMappers/DbTaskMapper.cs
  src/ProjectService.Mappers/RequestsMappers/Interfaces/IDbProjectMapper.cs
  src/ProjectService.Mappers/RequestsMappers/Interfaces/IDbTaskMapper.cs
  src/ProjectService.Mappers/RequestsMappers/Interfaces/IPatchDbTaskMapper.cs
  src/ProjectService.Models.Db/DbTask.cs
  src/ProjectService.Models.Dto/Requests/CreateTaskRequest.cs
  src/ProjectService.Validation/CreateProjectValidator.cs
  src/ProjectService.Validation/CreateTaskRequestValidator.cs
  src/ProjectService.Validation/ProjectUserValidator.cs
  test/ProjectService.Business.UnitTests/Commands/CreateTaskCommandTests.cs
  test/ProjectService.Mappers.UnitTests/RequestsMappers/DbTaskMapperTests.cs
Labels: bug

#62 Rework create project parameters request
  src/ProjectService.Data.Provider.MsSql.Ef/Migrations/20210707003534_ChangeTaskPropertiesAndProjectsTablesColumns.cs
  src/ProjectService.Validation/CreateProjectValidator.cs
  test/ProjectService.Validation.UnitTests/CreateProjectValidatorTests.cs
Labels: enhancement

#60 Get task
  src/ProjectService.Business/Commands/Task/EditTaskCommand.cs
  src/ProjectService.Business/Commands/Task/GetTaskCommand.cs
  src/ProjectService.Business/Commands/Task/Interfaces/IGetTaskCommand.cs
  src/ProjectService.Data/Interfaces/ITaskRepository.cs
  src/ProjectService.Data/TaskRepository.cs
  src/ProjectService.Mappers/Models/TaskInfoMapper.cs
  src/ProjectService.Mappers/Responses/Interfaces/ITaskResponseMapper.cs
  src/ProjectService.Mappers/Responses/TaskResponseMapper.cs
  src/ProjectService.Models.Db/DbTask.cs
  src/ProjectService.Models.Dto/Responses/TaskResponse.cs
  src/ProjectService.Validation/CreateTaskRequestValidator.cs
  src/ProjectService/Controllers/TaskController.cs
  test/ProjectService.Business.UnitTests/Commands/CreateProjectCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/EditTaskCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/FindProjectsCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/FindTasksCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/GetTaskCommandTests.cs
  test/ProjectService.Data.UnitTests/TaskRepositoryTests.cs
  test/ProjectService.Data.UnitTests/UserRepositoryTests.cs
  test/ProjectService.Mappers.UnitTests/Models/TaskInfoMapperTests.cs
  test/ProjectService.Mappers.UnitTests/Models/TaskPropertyInfoMapperTests.cs
  test/ProjectService.Mappers.UnitTests/Responses/TaskResponseMapperTests.cs
  test/ProjectService.Validation.UnitTests/CreateTaskValidationTests.cs
Labels: enhancement

#64 fix user/AddUsersToProject
  src/ProjectService.Business/Commands/AddUsersToProjectCommand.cs
  src/ProjectService.Data.Provider.MsSql.Ef/Migrations/20210711203811_RemoveForeignKey.cs
  src/ProjectService.Data/UserRepository.cs
  src/ProjectService.Validation/AddUsersToProjectValidator.cs
  test/ProjectService.Data.UnitTests/AddUsersToProjectRepositoryTests.cs
  test/ProjectService.Validation.UnitTests/AddUsersToProjectValidatorTests.cs
Labels: bug

#65 fix github actions
  .github/workflows/main.yml
Labels: documentation

#68 Update validation of optional string properties
  src/ProjectService.Business/Commands/Task/CreateTaskPropertyCommand.cs
  src/ProjectService.Mappers/RequestsMappers/DbProjectMapper.cs
  src/ProjectService.Mappers/RequestsMappers/DbTaskMapper.cs
  src/ProjectService.Mappers/RequestsMappers/DbTaskPropertyMapper.cs
  src/ProjectService.Validation/CreateProjectValidator.cs
  src/ProjectService.Validation/CreateTaskPropertyValidator.cs
  src/ProjectService.Validation/CreateTaskRequestValidator.cs
  test/ProjectService.Validation.UnitTests/CreateProjectValidatorTests.cs
  test/ProjectService.Validation.UnitTests/CreateTaskPropertyValidatorTests.cs
  test/ProjectService.Validation.UnitTests/CreateTaskValidationTests.cs
Labels: bug, enhancement

#70 fix find project
  src/ProjectService.Business/Commands/CreateProjectCommand.cs
  src/ProjectService.Models.Db/DbProject.cs
Labels: bug

#71 added unique constraint to Project name
  Common.Configurations.targets
  src/ProjectService.Business/Commands/CreateProjectCommand.cs
  src/ProjectService.Business/Commands/EditProjectCommand.cs
  src/ProjectService.Data.Provider.MsSql.Ef/Migrations/20210714130100_AddUniqueConstraintToProjectName.cs
  src/ProjectService.Data/Interfaces/IProjectRepository.cs
  src/ProjectService.Data/ProjectRepository.cs
  src/ProjectService.Data/TaskPropertyRepository.cs
  src/ProjectService.Data/TaskRepository.cs
  src/ProjectService.Data/UserRepository.cs
  src/ProjectService/Controllers/ProjectController.cs
  test/ProjectService.Data.UnitTests/FindProjectRepositoryTests.cs
  test/ProjectService.Data.UnitTests/TaskPropertyRepositoryTests.cs
  test/ProjectService.Data.UnitTests/TaskRepositoryTests.cs
Labels: bug

#74 docs/change_actions
  .github/workflows/main.yml
Labels: documentation

#73 fix find project
  src/ProjectService.Business/Commands/FindProjectsCommand.cs
  src/ProjectService.Data/Interfaces/IProjectRepository.cs
  src/ProjectService.Data/ProjectRepository.cs
  src/ProjectService.Data/TaskPropertyRepository.cs
  src/ProjectService.Data/TaskRepository.cs
  src/ProjectService.Mappers/RequestsMappers/FindDbProjectFilterMapper.cs
  src/ProjectService.Mappers/RequestsMappers/Interfaces/IFindDbProjectFilterMapper.cs
  src/ProjectService.Models.Dto/Requests/Filters/FindDbProjectsFilter.cs
  src/ProjectService.Models.Dto/Requests/Filters/FindProjectsFilter.cs
  test/ProjectService.Business.UnitTests/Commands/CreateProjectCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/FindProjectsCommandTests.cs
  test/ProjectService.Data.UnitTests/FindProjectRepositoryTests.cs
  test/ProjectService.Mappers.UnitTests/RequestsMappers/FindDbProjectFilterMapperTests.cs
Labels: bug

#75 Fixed check rights in find tasks endpoint
  src/ProjectService.Business/Commands/Task/FindTasksCommand.cs
  src/ProjectService.Data/TaskRepository.cs
  src/ProjectService.Models.Db/DbTask.cs
  test/ProjectService.Business.UnitTests/Commands/FindTasksCommandTests.cs
  test/ProjectService.Data.UnitTests/TaskRepositoryTests.cs
Labels: bug

#76 renamed uniqueConstraint
  src/ProjectService.Data.Provider.MsSql.Ef/Migrations/20210716155400_RenameUniqueConstraintFromNameToProjectName.cs
Labels: bug

#77 Fix find tasks
  src/ProjectService.Business/Commands/Task/FindTasksCommand.cs
  src/ProjectService.Data/TaskRepository.cs
Labels: bug

#82 Feature/updated kernel and responses
  Common.Configurations.targets
  src/ProjectService.Models.Dto/Enums/ProjectStatusType.cs
  src/ProjectService.Models.Dto/Enums/TaskPropertyType.cs
  src/ProjectService.Models.Dto/Enums/UserRoleType.cs
Labels: enhancement

#81 fix create task
  src/ProjectService.Business/Commands/Task/CreateTaskCommand.cs
  src/ProjectService.Data/UserRepository.cs
  src/ProjectService.Mappers/RequestsMappers/DbTaskMapper.cs
  src/ProjectService/Controllers/TaskController.cs
  test/ProjectService.Business.UnitTests/Commands/CreateTaskCommandTests.cs
Labels: bug

#80 fix find project command
  Common.Configurations.targets
  src/ProjectService.Business/Commands/FindProjectsCommand.cs
Labels: bug

#85 fix edit task
  src/ProjectService.Business/Commands/Task/EditTaskCommand.cs
  src/ProjectService.Validation/EditTaskValidator.cs
  src/ProjectService/Controllers/TaskController.cs
  test/ProjectService.Business.UnitTests/Commands/EditTaskCommandTests.cs
Labels: bug

#84 change class ro record
  src/ProjectService.Models.Dto/Models/AuthorInfo.cs
  src/ProjectService.Models.Dto/Models/DepartmentInfo.cs
  src/ProjectService.Models.Dto/Models/ProjectFileInfo.cs
  src/ProjectService.Models.Dto/Models/ProjectInfo.cs
  src/ProjectService.Models.Dto/Models/ProjectTaskInfo.cs
  src/ProjectService.Models.Dto/Models/TaskInfo.cs
  src/ProjectService.Models.Dto/Models/TaskProperty.cs
  src/ProjectService.Models.Dto/Models/TaskPropertyInfo.cs
  src/ProjectService.Models.Dto/Models/UserTaskInfo.cs
Labels: enhancement

#87 add find projects consumer
  Common.Configurations.targets
  src/ProjectService.Broker/FindProjectsConsumer.cs
  src/ProjectService.Data/Interfaces/IProjectRepository.cs
  src/ProjectService.Data/ProjectRepository.cs
  src/ProjectService.Models.Dto/Configurations/RabbitMqConfig.cs
  src/ProjectService/Startup.cs
  src/ProjectService/appsettings.json
Labels: enhancement

#86 fix get find edit tasks
  src/ProjectService.Business/Commands/Task/CreateTaskCommand.cs
  src/ProjectService.Business/Commands/Task/EditTaskCommand.cs
  src/ProjectService.Business/Commands/Task/FindTasksCommand.cs
  src/ProjectService.Business/Commands/Task/GetTaskCommand.cs
  src/ProjectService.Data/Interfaces/ITaskPropertyRepository.cs
  src/ProjectService.Data/Interfaces/ITaskRepository.cs
  src/ProjectService.Data/TaskPropertyRepository.cs
  src/ProjectService.Data/TaskRepository.cs
  src/ProjectService.Data/UserRepository.cs
  src/ProjectService.Mappers/Models/Interfaces/IUserTaskInfoMapper.cs
  src/ProjectService.Mappers/Models/TaskInfoMapper.cs
  src/ProjectService.Mappers/Models/UserTaskInfoMapper.cs
  src/ProjectService.Mappers/Responses/TaskResponseMapper.cs
  src/ProjectService.Models.Db/DbProjectUser.cs
  src/ProjectService.Models.Db/DbTask.cs
  src/ProjectService.Models.Db/DbTaskProperty.cs
  src/ProjectService.Models.Dto/Models/UserTaskInfo.cs
  src/ProjectService.Models.Dto/Responses/TaskResponse.cs
  src/ProjectService.Validation/CreateTaskRequestValidator.cs
  src/ProjectService.Validation/EditTaskValidator.cs
  test/ProjectService.Business.UnitTests/Commands/CreateTaskCommandTests.cs
  test/ProjectService.Data.UnitTests/TaskRepositoryTests.cs
  test/ProjectService.Mappers.UnitTests/Models/TaskInfoMapperTests.cs
  test/ProjectService.Mappers.UnitTests/Responses/TaskResponseMapperTests.cs
  test/ProjectService.Validation.UnitTests/EditTaskValidatorTests.cs
Labels: bug

#90 add users in find project
  Common.Configurations.targets
  src/ProjectService.Broker/GetProjectInfoConsumer.cs
  src/ProjectService.Business/Commands/Project/CreateProjectCommand.cs
  src/ProjectService.Business/Commands/Project/EditProjectCommand.cs
  src/ProjectService.Business/Commands/Project/FindProjectsCommand.cs
  src/ProjectService.Business/Commands/Project/GetProjectCommand.cs
  src/ProjectService.Business/Commands/Project/Interfaces/ICreateProjectCommand.cs
  src/ProjectService.Business/Commands/Project/Interfaces/IEditProjectCommand.cs
  src/ProjectService.Business/Commands/Project/Interfaces/IFindProjectsCommand.cs
  src/ProjectService.Business/Commands/Project/Interfaces/IGetProjectCommand.cs
  src/ProjectService.Business/Commands/ProjectUsers/AddUsersToProjectCommand.cs
  src/ProjectService.Business/Commands/ProjectUsers/DisableWorkersInProjectCommand.cs
  src/ProjectService.Business/Commands/ProjectUsers/Interfaces/IAddUsersToProjectCommand.cs
  src/ProjectService.Business/Commands/ProjectUsers/Interfaces/IDisableWorkersInProject.cs
  src/ProjectService.Data/Interfaces/IProjectRepository.cs
  src/ProjectService.Data/Interfaces/IUserRepository.cs
  src/ProjectService.Data/ProjectRepository.cs
  src/ProjectService.Data/UserRepository.cs
  src/ProjectService.Mappers/Models/Interfaces/IProjectUserInfoMapper.cs
  src/ProjectService.Mappers/Models/ProjectUserInfoMapper.cs
  src/ProjectService.Models.Dto/Configurations/RabbitMqConfig.cs
  src/ProjectService.Models.Dto/Models/PositionInfo.cs
  src/ProjectService.Models.Dto/Models/ProjectUser/ProjectUserInfo.cs
  src/ProjectService/Controllers/ProjectController.cs
  src/ProjectService/Controllers/UserController.cs
  src/ProjectService/appsettings.json
  test/ProjectService.Broker.UnitTests/GetProjectInfoConsumerTests.cs
  test/ProjectService.Business.UnitTests/Commands/AddUsersToProjectCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/DisableWorkersInProjectCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/EditProjectCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/FindTasksCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/GetProjectCommandTests.cs
  test/ProjectService.Data.UnitTests/FindProjectRepositoryTests.cs
  test/ProjectService.Data.UnitTests/GetProjectByIdRepositoryTests.cs
  test/ProjectService.Mappers.UnitTests/Models/ProjectUserInfoMapperTests.cs
  test/ProjectService.Mappers.UnitTests/Models/TaskInfoMapperTests.cs
Labels: enhancement
