Repository LT-Students/DigitalOffice-ProjectService, pull requests merged in 2022-08, with the labels that each got.

#179 Feature/add project activation work time
  Common.Configurations.targets
  src/ProjectService.Broker/Consumers/GetProjectsUsersConsumer.cs
  src/ProjectService.Business/Commands/Project/CreateProjectCommand.cs
  src/ProjectService.Business/Commands/Project/EditProjectCommand.cs
  src/ProjectService.Business/Commands/ProjectUsers/CreateProjectUsersCommand.cs
  src/ProjectService.Data/ProjectUserRepository.cs
  src/ProjectService.Mappers/PatchDocument/PatchDbProjectMapper.cs
Labels: enhancement

#183 Added file access
  src/ProjectService.Business/Commands/File/FindFilesCommand.cs
  src/ProjectService.Business/Commands/File/Interfaces/IFindFilesCommand.cs
  src/ProjectService.Mappers/Models/FileAccessMapper.cs
  src/ProjectService.Mappers/Models/FileInfoMapper.cs
  src/ProjectService.Mappers/Models/Interfaces/IFileAccessMapper.cs
  src/ProjectService.Mappers/Models/Interfaces/IFileInfoMapper.cs
  src/ProjectService.Models.Dto/Models/FileAccess.cs
  src/ProjectService.Models.Dto/Models/FileInfo.cs
  src/ProjectService/Controllers/FileController.cs
Labels: enhancement

#182 Add project existence
  Common.Configurations.targets
  src/ProjectService.Broker/Consumers/GetProjectUserRoleConsumer.cs
  src/ProjectService.Business/Commands/File/FindFilesCommand.cs
  src/ProjectService.Business/Commands/Project/CreateProjectCommand.cs
  src/ProjectService.Business/Commands/Project/EditProjectCommand.cs
  src/ProjectService.Business/Commands/ProjectUsers/CreateProjectUsersCommand.cs
  src/ProjectService.Data/Interfaces/IProjectRepository.cs
  src/ProjectService.Data/Interfaces/IProjectUserRepository.cs
  src/ProjectService.Data/ProjectRepository.cs
  src/ProjectService.Data/ProjectUserRepository.cs
  src/ProjectService.Mappers/Models/ProjectInfoMapper.cs
  src/ProjectService.Mappers/PatchDocument/PatchDbProjectMapper.cs
  src/ProjectService.Models.Dto/Configurations/RabbitMqConfig.cs
  src/ProjectService.Models.Dto/Enums/ProjectStatusType.cs
  src/ProjectService.Models.Dto/Models/ProjectInfo.cs
  src/ProjectService.Models.Dto/Requests/Project/CreateProjectRequest.cs
  src/ProjectService.Models.Dto/Requests/Project/EditProjectRequest.cs
  src/ProjectService.Models.Dto/Requests/Project/FindProjectsFilter.cs
  src/ProjectService.Validation/Project/CreateProjectRequestValidator.cs
  src/ProjectService.Validation/Project/EditProjectRequestValidator.cs
  src/ProjectService/Startup.cs
  src/ProjectService/UserController.cs
  src/ProjectService/appsettings.json
Labels: bug

#185 update GetProjects consumer
  Common.Configurations.targets
  src/ProjectService.Broker/Consumers/GetProjectsConsumer.cs
  src/ProjectService.Data/ProjectRepository.cs
  src/ProjectService.Mappers/Models/Interfaces/IProjectDepartmentDataMapper.cs
  src/ProjectService.Mappers/Models/ProjectDepartmentDataMapper.cs
Labels: enhancement

#186 Added edit endpoint
  src/ProjectService.Business/Commands/File/EditFilesCommand.cs
  src/ProjectService.Business/Commands/File/Interfaces/IEditFilesCommand.cs
  src/ProjectService.Business/Commands/File/RemoveFilesCommand.cs
  src/ProjectService.Data/Interfaces/IProjectFileRepository.cs
  src/ProjectService.Data/ProjectFileRepository.cs
  src/ProjectService/Controllers/FileController.cs
  src/ProjectService/Startup.cs
Labels: enhancement

#187 update GetProjectsConsumer
  Common.Configurations.targets
  src/ProjectService.Broker/Consumers/GetProjectUserRoleConsumer.cs
  src/ProjectService.Broker/Consumers/GetProjectsConsumer.cs
  src/ProjectService.Data/Interfaces/IProjectRepository.cs
  src/ProjectService.Data/ProjectRepository.cs
  src/ProjectService.Data/ProjectUserRepository.cs
Labels: enhancement

#188 remove unused request
  src/ProjectService.Broker/Requests/Interfaces/IUserService.cs
  src/ProjectService.Broker/Requests/UserService.cs
  src/ProjectService.Data/ProjectRepository.cs
  src/ProjectService.Models.Dto/Configurations/RabbitMqConfig.cs
  src/ProjectService/appsettings.json
Labels: bug, enhancement

#189 Mock files
  src/ProjectService.Broker/Requests/FileService.cs
  src/ProjectService.Data/ProjectFileRepository.cs
  test/ProjectService.Business.UnitTests/Commands/CreateProjectCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/GetProjectCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/Project/CreateProjectCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/Project/EditProjectCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/Project/FindProjectsCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/Project/GetProjectCommandTests.cs
Labels: enhancement

#192 Fixed error with parametrs
  src/ProjectService.Business/Commands/Image/CreateImageCommand.cs
  src/ProjectService.Business/Commands/Image/RemoveImageCommand.cs
  src/ProjectService.Business/Commands/ProjectUsers/CreateProjectUsersCommand.cs
  src/ProjectService.Business/Commands/ProjectUsers/RemoveProjectUsersCommand.cs
Labels: bug

#193 Changed response
  src/ProjectService.Mappers/Models/ProjectInfoMapper.cs
  src/ProjectService.Mappers/Responses/ProjectResponseMapper.cs
  src/ProjectService.Models.Dto/Models/ProjectInfo.cs
  src/ProjectService.Models.Dto/Responses/ProjectResponse.cs
  src/ProjectService/Startup.cs
  test/ProjectService.Business.UnitTests/Commands/Project/GetProjectCommandTests.cs
  test/ProjectService.Mappers.UnitTests/Responses/ProjectResponseMapperTests.cs
Labels: enhancement

#191 Add tests and small fixe
  src/ProjectService.Business/Commands/Department/EditProjectDepartmentCommand.cs
  src/ProjectService.Business/Commands/Image/CreateImageCommand.cs
  src/ProjectService.Business/Commands/Image/RemoveImageCommand.cs
  src/ProjectService.Business/Commands/ProjectUsers/RemoveProjectUsersCommand.cs
  test/ProjectService.Business.UnitTests/Commands/Department/EditProjectDepartmentCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/Project/EditProjectCommandTests.cs
  test/ProjectService.Business.UnitTests/Commands/Project/FindProjectsCommandTests.cs
Labels: enhancement

#195 fix GetProjectWithUserAsync
  src/ProjectService.Data/ProjectRepository.cs
Labels: bug

#199 Add tests in repositories
  src/ProjectService.Data/ProjectRepository.cs
  src/ProjectService.Data/ProjectUserRepository.cs
  src/ProjectService.Models.Db/DbProjectDepartment.cs
  src/ProjectService.Models.Db/DbProjectFile.cs
  src/ProjectService.Models.Db/DbProjectImage.cs
  src/ProjectService.Models.Db/DbProjectUser.cs
  src/ProjectService.Models.Dto/Requests/User/EditProjectUsersRoleRequest.cs
  test/ProjectService.Data.UnitTests/AddUsersToProjectRepositoryTests.cs
  test/ProjectService.Data.UnitTests/CreateNewProjectRepositoryTests.cs
  test/ProjectService.Data.UnitTests/DisableWorkersInProjectRepositoryTests.cs
  test/ProjectService.Data.UnitTests/EditProjectRepositoryTests.cs
  test/ProjectService.Data.UnitTests/FindProjectRepositoryTests.cs
  test/ProjectService.Data.UnitTests/GetProjectByIdRepositoryTests.cs
  test/ProjectService.Data.UnitTests/GetProjectUsersRepositoryTests.cs
  test/ProjectService.Data.UnitTests/ProjectImageRepositoryTests.cs
  test/ProjectService.Data.UnitTests/ProjectRepositoryTests.cs
  test/ProjectService.Data.UnitTests/ProjectUserRepositoryTests.cs
  test/ProjectService.Data.UnitTests/UserRepositoryTests.cs
Labels: enhancement
